version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo "Installing ansible"
      - pip install ansible==2.9.6
      - echo "Installing Packer"
      - curl -qL -o packer.zip https://releases.hashicorp.com/packer/1.7.8/packer_1.7.8_linux_amd64.zip && unzip packer.zip
  pre_build:
    commands:
      - echo "Updating the repository"
      - apt-get update -y
      - echo "Packer init"
      - ./packer init -upgrade packer.pkr.hcl
      - echo "Validating the Packer template"
      - ./packer validate packer.pkr.hcl
  build:
    commands:
       - echo "Building the Packer template"
       - ./packer build packer.pkr.hcl